version: "3"

services:
  tg_bot:
    build: .
    container_name: tg_stats_bot
    env_file:
      - .env
    volumes:
      - /www/tg_bot/logs:/app/logs
      - /www/tg_bot/db:/app/db
      - /var/run/docker.sock:/var/run/docker.sock
    command: python run.py
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
